// <auto-generated />
using System;
using TimesheetReportGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TimesheetReportGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805152151_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimesheetReportGenerator.Models.TicketTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("TicketDate")
                        .HasColumnType("date");

                    b.Property<string>("TicketDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TicketId")
                        .HasColumnType("longtext");

                    b.Property<float>("TimeSpent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TicketTrackings");
                });
#pragma warning restore 612, 618
        }
    }
}
